cache: pip
install: true
branches:
  only:
    - master

language: python
matrix:
  include:

  - name: "Python 3.6"
    python: "3.6"
    before_script:
      - make install
    script:
      - flake8
      - make tests

  - name: "Python 2.7"
    python: "2.7"
    before_script:
      - make install
    script:
      - flake8
      - make tests
      - make is_newest_version
    deploy:
      - provider: script
        script: make publish
        skip_cleanup: true
        on:
            branch: master

notifications:
  slack: pymetrics:KChIHKNZmyRqFuUPC0IQBocG
