language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
cache:
  - pip

install:
  - make install
  - pip install flake8

script:
  - flake8
  - make is_newest_version
  - make tests

branches:
only:
  - master

notifications:
  slack: pymetrics:KChIHKNZmyRqFuUPC0IQBocG
